title: Yongliang Miao
position: Ph.D. Student in Artificial Intelligence
affiliation: The Chinese University of Hong Kong, Shenzhen
email: r130026108@gmail.com
description: Yongliang Miao researches efficient post-training and data selection and generation for large language models at The Chinese University of Hong Kong, Shenzhen.
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - html_source_file/

  - minimal-light.gemspec
  - html_source_file/
